dj3/my_site/my_app/urls.py
from django.urls import path
from . import views

app_name = "my_app"  # used in {% url '...'%}

urlpatterns = [
    path("", views.example_view, name="example_view"),
    path("variable/", views.variable_view, name="variable_view"),
]

dj3/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("my_app/", include("my_app.urls")),
]

handler500 = "my_site.views.my_custom_server_error_view"

dj3/my_site/my_app/models.py
from django.db import models

# Create your models here.

dj3/my_site/my_app/views.py
from django.shortcuts import render

# Create your views here.


def example_view(request):
    return render(request, "my_app/example.html")


# {%%} = django tag, where we place control flow and loops
# {{}} = django variable
def variable_view(request):

    my_var = {
        "first_name": "Red",
        "last_name": "fUSCHIA",
        "some_list": [1, 2, 3],
        "some_dictionary": {"i_k1": "i_v1", "i_k2": "i_v2", "i_k3": "i_v3"},
        "user_logged_in": True,
    }

    return render(request, "my_app/variable.html", context=my_var)

dj3/my_site/my_site/views.py
from django.shortcuts import render


def my_custom_server_error_view(request, *args, **argv):
    return render(request, "error_view.html", status=500)

dj3/my_site/my_app/templates/my_app/example.html
{% extends 'base.html' %}
{% load static %}

{% block block_name1 %}
  <h1>my_app</h1>
  <a href="{% url 'my_app:variable_view' %}">open variable.html</a>
  <img src="{% static 'my_app/Django_Unchained.jpg' %}" alt="Django_Unchained image">
{% endblock %}

dj3/my_site/my_app/templates/my_app/variable.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>VARIABLE.HTML</h1>




    <ul>
      {% for i in some_list %}
        <li>{{i}}</li>
      {% endfor %}
    </ul>

    <ol>
      {% for k,v in some_dictionary.items %}
        <li>{{k}} {{v}}</li>
      {% endfor %}
    </ol>

    {% if user_logged_in %}
      <span>user logged in.</span>
    {% endif %}

    <ul>
      {% if some_list|length > 0 %}
        number of list items: {{some_list|length}}
      {% endif %}
      {% for num in some_list %}
        {% if num == 2 %}
          <li>TWO</li>
        {% else %}
          <li>{{num}}</li>
        {% endif %}
      {% endfor %}
    </ul>

    <!-- django filters using | sign -->
    <!-- <h2>First name was: {{first_name|upper}}</h2>
    <h2>Last name was: {{last_name|lower|capfirst}}</h2>
    <h3>{{some_list.0}}</h3>
    <h3>{{some_dictionary.i_k}}</h3>
    <h4>{# this is a comment #}</h4> -->
  </body>
</html>

dj3/my_site/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>base</title>
</head>
<body>
  <h1>this is above the block in base.html</h1>
  {% block block_name1 %}
  {% endblock %}
  <h1>this is below the block in base.html</h1>
</body>
</html>

dj3/my_site/templates/error_view.html
custom 500 error